{% set name = "psiexperiment" %}
{% set version = "0.1.5rc4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 58a7878918518e3235107b5388519b084211a63bb4344f8058e1ad008ca110ce

build:
  noarch: python

  # Increment if this is a new build for the same version.
  number: 1

  entry_points:
    - psi=psi.application.psi_launcher:main
    - psi-config=psi.application:config
    - psi-behavior=psi.application.base_launcher:main_animal
    - psi-calibration=psi.application.base_launcher:main_calibration
    - psi-cfts=psi.application.base_launcher:main_ear
    - psi-cohort=psi.application.base_launcher:main_cohort
    - psi-summarize-abr=psi.data.io.summarize_abr:main
    - psi-summarize-abr-gui=psi.data.io.summarize_abr:main_gui
    - psi-summarize-abr-auto=psi.data.io.summarize_abr:main_auto

  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python >=3.7
    - enaml >=0.10.4
    - numpy >=1.18
    - matplotlib >= 3.3.2
    - pandas >= 1.1.3
    - scipy >=1.3.1
    - psi-bcolz >=1.2.2
    - palettable >=3.3.0
    - pyqtgraph >=0.11.0
    - tqdm
    - pydaqmx >=1.4.5
    - tdtpy

test:
  imports:
    - psi
    - psi.application
    - psi.application.experiment
    - psi.context.api
    - psi.controller.api
    - psi.controller.calibration.api
    - psi.controller.devices
    - psi.controller.engines
    - psi.core
    - psi.core.enaml.api
    - psi.data.api
    - psi.data.io.api
    - psi.data.sinks.api
    - psi.experiment.api
    - psi.token.api
  commands:
    - psi-config --help
    - psi-summarize-abr --help
    - psi-summarize-abr-gui --help
    - psi-summarize-abr-auto --help

about:
  home: https://github.com/psiexpeirment/psiexperiment
  license: BSD 3-clause
  license_family: BSD
  summary: "Module for running auditory experiments."
  doc_url: https://psiexperiment.readthedocs.io
  dev_url: https://github.com/psiexpeirment/psiexperiment

extra:
  recipe-maintainers:
    - bburan
    - buranconsult
