{% set name = "PyDAQmx" %}
{% set version = "1.4.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/psiexperiment/PyDAQmx
  git_rev: "v{{ version }}"

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "http://pythonhosted.org/PyDAQmx/"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Interface to the National Instruments PyDAQmx driver"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - bburan
